### ISSUE TITLE
Blender script doesn't work with Cauldron Born/Bushwacker

### ISSUE THREAD

**Issue by tobywf** [tobywf/mech3ax-py#5]
## MechWarrior 3 version

Version 1.00 (U.S.)
Version 1.01 (U.S.)
Version 1.02 (U.S.)
Version 1.00 (Deutsch)

- [x] I'm using an original CD
- [x] I'm willing to provide a copy of the file causing the issue for debugging
- [x] Not Pirate's Moon expansion

## What happened?

Export script errors out when converting `mech_bushwacker.json` and `mech_cauldron.json` with "face already exists".

## Steps to Reproduce

Operating system: Windows 10, macOS Sierra (10.12)
Python version: Python 3.7.3 (default, Mar 27 2019, 09:23:32)
Blender version: Blender 2.80 (sub 74) (hash 06312c6d2db8 built 2019-07-11 19:16:32)

- [x] I'm using a Python version of 3.7 or higher
- [x] I'm using a Blender version of 2.80 or higher
- [x] I'm using a virtual environment

1. Export 'mechs
1. Try to run script with against `mech_bushwacker.json` or `mech_cauldron.json`

 ```
blender \
    --background 
    --factory-startup \
    --python model2blend.py -- \
    mechlib/mech_bushwacker.json mechtex/
```

3. Results in `ValueError: faces.new(verts): face already exists`

## Detailed Description

```pycon
Traceback (most recent call last):
  File "mech3ax/model2blend.py", line 268, in <module>
    main()
  File "mech3ax/model2blend.py", line 264, in main
    model_to_blend(args.model, args.tex_dir, blend_path, materials, args.anim)
  File "mech3ax/model2blend.py", line 179, in model_to_blend
    root = _create_objects(model, None, get_material)
  File "mech3ax/model2blend.py", line 76, in _create_objects
    _create_objects(child, obj, get_material)
  File "mech3ax/model2blend.py", line 76, in _create_objects
    _create_objects(child, obj, get_material)
  File "mech3ax/model2blend.py", line 76, in _create_objects
    _create_objects(child, obj, get_material)
  File "mech3ax/model2blend.py", line 56, in _create_objects
    face = bm.faces.new(bm.verts[i] for i in vertex_indices)
ValueError: faces.new(verts): face already exists
```

**Comment by tobywf** [comment]
(Doesn't happen with lower-poly versions `mech_bushwacker_1.json` and `mech_cauldron_1.json`)

**Comment by tobywf** [comment]
Also happens with `mech_annihilator_1.json` and `mech_strider_1.json`.

**Comment by tobywf** [comment]
I've spot-checked, and the polygons are exactly the same. So it seems safe to ignore the duplicate faces. Should be fixed in the next push.
